version: "3.8"

services:
    database:
        image: postgres
        container_name: database_hackathon
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=hackathon
            - POSTGRES_PASSWORD=hackathon
            - POSTGRES_DB=hackathon
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: hackathon
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local
